### ISSUE TITLE
Incorrect download path for covers

### ISSUE THREAD

**Issue by apetresc** [djdembeck/m4b-merge#103]
The code for downloading the cover [is set to](https://github.com/djdembeck/m4b-merge/blob/e401a0c2f08e1182a86d0fa677d13e527eb57113/src/m4b_merge/m4b_helper.py#L32):

```python
self.cover_path = f"{self.input_path}_cover.jpg"
```

This makes no sense. If my input path is `/input` (as is recommended for the Docker-based install), then the script will attempt to download the temporary cover file to `/input_cover.jpg` which is in `/` and will probably fail with:

```sh
Traceback (most recent call last):
  File "/usr/local/bin/m4b-merge", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/m4b_merge/__main__.py", line 147, in main
    validate_args(parser.parse_args())
  File "/usr/local/lib/python3.10/site-packages/m4b_merge/__main__.py", line 92, in validate_args
    run_all(input_path)
  File "/usr/local/lib/python3.10/site-packages/m4b_merge/__main__.py", line 33, in run_all
    m4b.run_merge()
  File "/usr/local/lib/python3.10/site-packages/m4b_merge/m4b_helper.py", line 258, in run_merge
    self.prepare_command_args()
  File "/usr/local/lib/python3.10/site-packages/m4b_merge/m4b_helper.py", line 108, in prepare_command_args
    self.download_cover()
  File "/usr/local/lib/python3.10/site-packages/m4b_merge/m4b_helper.py", line 34, in download_cover
    with open(self.cover_path, 'wb') as f:
PermissionError: [Errno 13] Permission denied: '/input_cover.jpg'
```

I think what you meant was

```python
self.cover_path = self.input_path / "cover.jpg"
```

(assuming that `self.input_path` is a `pathlib.Path` object rather than a `string` of course).

**Comment by apetresc** [comment]
Opened a pull request #104 with a hopefully reasonable fix for this bug. Tested locally on my Docker setup and it works fine there.
