### ISSUE TITLE
Docker Issue

### ISSUE THREAD

**Issue by epthewizard** [djdembeck/m4b-merge#283]
I am getting a couple errors when trying to run the Docker container:

Starting with UID: 99, GID: 100
chown: /config: No such file or directory
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/pathlib.py", line 1116, in mkdir
    os.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/.config/m4b-merge'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/m4b-merge", line 5, in <module>
    from m4b_merge.__main__ import main
  File "/usr/local/lib/python3.11/site-packages/m4b_merge/__main__.py", line 6, in <module>
    from . import audible_helper, config, helpers, m4b_helper
  File "/usr/local/lib/python3.11/site-packages/m4b_merge/config.py", line 11, in <module>
    Path(config_path).mkdir(
  File "/usr/local/lib/python3.11/pathlib.py", line 1120, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.11/pathlib.py", line 1116, in mkdir
    os.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/.config'

I've tried to change the UID and GID but nothing works. Any help? Appreciated it

**Comment by djdembeck** [comment]
What command are you starting the docker with?

**Comment by brahma-dev** [comment]
`docker run -e UID=1000 -e GID=1000 --name=merge -v $PWD:/input -v $PWD:/output -it ghcr.io/djdembeck/m4b-merge:v0.5.3`

**Comment by HDS-nlucas** [comment]
Same exact issue here. 

Using the command shown: docker run --name=merge -v /my/input:/input -v /my/output:/output ghcr.io/djdembeck/m4b-merge:main

**Comment by chriscarpenter12** [comment]
Seeing the same issue on `main` too

**Comment by djdembeck** [comment]
Thanks for reporting this! The Rust rewrite has completely replaced the Python-based Docker setup with a new Alpine/musl Dockerfile that uses proper non-root user handling and mounts , , and  directories directly. The permission errors from the old Python implementation no longer apply.

Closing this — if you run into anything with the new Docker image, please let us know!
